name: localized_hello
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/Vanethos/flutter_localized_hello

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  intl_translation: ^0.17.9
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
